[tool.pylint.messages_control]
disable = [
  "C0103",
  "C0121",
  "C0411",
  "C0413",
  "E0611",
  "R0903",
  "W0511",
  "W0622",
  "W0611",
]

[tool.pylint.format]
indent-string="  "

[tool.pytest.ini_options]
pythonpath  = "vehicle_api"
addopts     = "-ra -v --disable-warnings" # -ra => full test summary

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
name        = "vehicle-api"
version     = "0.1.0"
description = "vehicle-api"
authors     = ["Schroettinger, Dominik <dominik.schroettinger@devoteam.com>"]
readme      = "README.md"

[tool.poetry.dependencies]

python = "~3.11.0" # => Used by Î»-Service

[tool.poetry.dev-dependencies]
pre-commit = "^3.4.0"

boto3 = "^1.28.60"

aws-lambda-powertools = "^2.25.0"
pydantic = "^1.10.10"

python-dotenv = "^1.0.0"

pylint = "^3.0.0"

pydantic-factories = "^1.17.0"
freezegun          = "^1.2.0"
coverage           = "^7.3.2"
pytest             = "^7.3.2"
