# name: ci

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     services:
#       dynamodb:
#         image: amazon/dynamodb-local
#         ports:
#           - 8000:8000
#     steps:
#       - name: Harden Runner
#         uses: step-security/harden-runner@v2
#         with:
#           egress-policy: audit

#       - name: Check-Out
#         uses: actions/checkout@v3

#       - run:  pipx install poetry~=1.4.0
#         name: Install Poetry
#       - name: Install Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.11 # => Required by Î»-Service
#           cache: poetry

#       - run:  poetry install
#         name: Install Dependencies

#       - run:  poetry run pytest tests/unit
#         name: Unit-Tests

#       - run:  poetry run pytest tests/intr
#         name: Intr-Tests
